name: Build and deploy website

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 12 * *"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build
      run: python build.py --username ${{ github.actor }}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: ${{ github.actor }}/${{ github.actor }}.github.io
        publish_branch: gh-pages
        publish_dir: ./output
        force_orphan: true
